project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!emails/*"
  resources:
    - calendar/
    # - emails/

website:
  title: "MACSI Seminar Series"
  site-url: ""
  favicon: MACSI_small.png
  navbar:
    collapse-below: lg
    left:
      - text: "AY25-26 Semesters 2 (current)"
        file: index.qmd
      - text: "AY26-27 Semesters 1 (future)"
        file: create_AY26-27_sem_1_timetable.qmd
      - text: "Previous Semesters"
        menu:
          - text: "AY25-26 Semesters 1"
            file: create_AY25-26_sem_1_timetable.qmd
          - text: "AY24-25 Semesters 2"
            file: create_AY24-25_sem_2_timetable.qmd
          - text: "AY24-25 Semesters 1"
            file: create_AY24-25_sem_1_timetable.qmd
          - text: "AY23-24 Semesters 2"
            file: create_AY23-24_sem_2_timetable.qmd
format:
  html:
    theme: flatly
    toc: true
    toc-expand: true
    anchor-sections: true
    smooth-scroll: true
    css: styles.css       
    include-before-body: _partials/banner.html
